name: Check self-hosted runner

on:
  push:
    branches:
      - master
      
jobs:
  test-1:
    runs-on: [self-hosted, 2-gpus]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Show info
      run: |
        python --version
        nvidia-smi
        ls /
        ls /home
        docker ps -a
      
