name: Build And Publish Docker Images

on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:


jobs:
  build-publish:
    name: Build and Push Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger Circle-CI pipeline
        run: |
          if [ $GITHUB_EVENT_PATH == 'pull_request' ]; then should_publish_docker_images=false; else should_publish_docker_images=true; fi
          if [ $GITHUB_EVENT_PATH == 'pull_request' ]; then branch=$GITHUB_HEAD_REF; else branch=$GITHUB_REF; fi
          echo "should_publish_docker_images=$should_publish_docker_images"
          echo "branch=$branch"
          echo "sh .github/workflows/trigger_circle_ci.sh $should_publish_docker_images $branch"
